project:
  type: website

website:
  title: "我的学习网站"
  navbar:
    left:
      - href: index.qmd
        text: 关于我
      - href: lab.qmd
        text: 实验室
    right:
      - icon: github
        href: https://github.com/yourusername
        text: "GitHub"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
